packages:
  - apps/*
  - packages/*

# catalog:
#   "@types/node": ^24.5.2
#   "@types/react": ^19.2.1
#   "@types/react-dom": ^19.2.1
#   class-variance-authority: 0.7.1
#   clsx: ^2.1.1
#   lucide-react: 0.544.0
#   next: ^15.5.4
#   react: 19.2.0
#   react-dom: ^19.2.0
#   tailwind-merge: ^3.3.1
#   tailwindcss: ^4.1.14
#   tw-animate-css: ^1.4.0
#   typescript: 5.9.3
#   vite: ^7.1.9
#   zod: 4.1.11
