/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  index: {
    name: "index",
    description: "",
    type: "registry:style",
    dependencies: ["class-variance-authority", "lucide-react", "uilab-core"],
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  style: {
    name: "style",
    description: "",
    type: "registry:style",
    dependencies: ["class-variance-authority", "lucide-react", "uilab-core"],
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "currency-input": {
    name: "currency-input",
    description: "Input for currencies :)",
    type: "registry:component",
    dependencies: ["react-hook-form", "react-number-format", "uilab-core"],
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/ui/currency-input.tsx",
        type: "registry:component",
        target: "",
        content: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/ui/currency-input.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  confirmation: {
    name: "confirmation",
    description: "",
    type: "registry:block",
    dependencies: ["lucide-react", "uilab-core"],
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/blocks/confirmation.tsx",
        type: "registry:component",
        target: "components/confirmation.tsx",
        content: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/blocks/confirmation.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["dialog"],
    meta: undefined,
  },
  "data-table": {
    name: "data-table",
    description: "",
    type: "registry:block",
    dependencies: ["@tanstack/react-table", "lucide-react", "uilab-core"],
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/blocks/data-table/advanced.tsx",
        type: "registry:component",
        target: "components/data-table/advanced.tsx",
        content: "",
      },
      {
        path: "registry/classic/blocks/data-table/basic.tsx",
        type: "registry:component",
        target: "components/data-table/basic.tsx",
        content: "",
      },
      {
        path: "registry/classic/blocks/data-table/filter-popover.tsx",
        type: "registry:component",
        target: "components/data-table/filter-popover.tsx",
        content: "",
      },
      {
        path: "registry/classic/blocks/data-table/merged-cell.tsx",
        type: "registry:component",
        target: "components/data-table/merged-cell.tsx",
        content: "",
      },
      {
        path: "registry/classic/blocks/data-table/pagination.tsx",
        type: "registry:component",
        target: "components/data-table/pagination.tsx",
        content: "",
      },
      {
        path: "registry/classic/blocks/data-table/index.tsx",
        type: "registry:component",
        target: "components/data-table/index.tsx",
        content: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/classic/blocks/data-table/advanced.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["data", "table"],
    meta: undefined,
  },
  "data-list": {
    name: "data-list",
    description: "",
    type: "registry:component",
    dependencies: [
      "@base-ui/react",
      "class-variance-authority",
      "uilab-core",
    ],
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/blocks/data-list.tsx",
        type: "registry:component",
        target: "components/data-list.tsx",
        content: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/blocks/data-list.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["data", "list"],
    meta: undefined,
  },
  "form-dialog": {
    name: "form-dialog",
    description: "",
    type: "registry:block",
    dependencies: ["react-hook-form", "lucide-react", "uilab-core"],
    registryDependencies: [
      "https://ailabmn.gitlab.io/frontend/uilab/registry/r/confirmation.json",
    ],
    files: [
      {
        path: "registry/classic/blocks/form-dialog.tsx",
        type: "registry:component",
        target: "components/form-dialog.tsx",
        content: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/blocks/form-dialog.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["dialog", "form"],
    meta: undefined,
  },
  "form-sheet": {
    name: "form-sheet",
    description: "",
    type: "registry:block",
    dependencies: ["react-hook-form", "lucide-react", "uilab-core"],
    registryDependencies: [
      "https://ailabmn.gitlab.io/frontend/uilab/registry/r/confirmation.json",
    ],
    files: [
      {
        path: "registry/classic/blocks/form-sheet.tsx",
        type: "registry:component",
        target: "components/form-sheet.tsx",
        content: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/blocks/form-sheet.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["sheet", "form"],
    meta: undefined,
  },
  sonner: {
    name: "sonner",
    description: "",
    type: "registry:block",
    dependencies: ["uilab-core", "lucide-react", "next-themes"],
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/blocks/sonner.tsx",
        type: "registry:component",
        target: "components/sonner.tsx",
        content: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/blocks/sonner.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["toaster"],
    meta: undefined,
  },
  "confirmation-demo": {
    name: "confirmation-demo",
    description: "",
    type: "registry:example",
    dependencies: ["lucide-react", "uilab-core"],
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/examples/confirmation-demo.tsx",
        type: "registry:example",
        target: "",
        content: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/classic/examples/confirmation-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "data-list-demo": {
    name: "data-list-demo",
    description: "",
    type: "registry:example",
    dependencies: [
      "@base-ui/react",
      "class-variance-authority",
      "uilab-core",
    ],
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/examples/data-list-demo.tsx",
        type: "registry:example",
        target: "",
        content: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/classic/examples/data-list-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "sonner-demo": {
    name: "sonner-demo",
    description: "",
    type: "registry:example",
    dependencies: ["sonner", "next-themes", "uilab-core"],
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/examples/sonner-demo.tsx",
        type: "registry:example",
        target: "",
        content: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/examples/sonner-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
};
