/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  index: {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  style: {
    name: "style",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "currency-input": {
    name: "currency-input",
    description: "Input for currencies :)",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/ui/currency-input.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/ui/currency-input.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  confirmation: {
    name: "confirmation",
    description: "Common extendable confirmation dialog for uilab",
    type: "registry:block",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/blocks/confirmation.tsx",
        type: "registry:component",
        target: "components/confirmation.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/blocks/confirmation.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["dialog"],
    meta: undefined,
  },
  "data-table": {
    name: "data-table",
    description: "Common extendable data table for uilab",
    type: "registry:block",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/blocks/data-table/advanced.tsx",
        type: "registry:component",
        target: "components/data-table/advanced.tsx",
      },
      {
        path: "registry/classic/blocks/data-table/basic.tsx",
        type: "registry:component",
        target: "components/data-table/basic.tsx",
      },
      {
        path: "registry/classic/blocks/data-table/filter-popover.tsx",
        type: "registry:component",
        target: "components/data-table/filter-popover.tsx",
      },
      {
        path: "registry/classic/blocks/data-table/merged-cell.tsx",
        type: "registry:component",
        target: "components/data-table/merged-cell.tsx",
      },
      {
        path: "registry/classic/blocks/data-table/pagination.tsx",
        type: "registry:component",
        target: "components/data-table/pagination.tsx",
      },
      {
        path: "registry/classic/blocks/data-table/index.tsx",
        type: "registry:component",
        target: "components/data-table/index.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/classic/blocks/data-table/advanced.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["data", "table"],
    meta: undefined,
  },
  "data-list": {
    name: "data-list",
    description: "Data list component",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/classic/blocks/data-list.tsx",
        type: "registry:component",
        target: "components/data-list.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/blocks/data-list.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["data", "list"],
    meta: undefined,
  },
  "form-dialog": {
    name: "form-dialog",
    description: "Common dialog of a form component",
    type: "registry:block",
    registryDependencies: [
      "https://ailabmn.gitlab.io/frontend/uilab/registry/r/confirmation.json",
    ],
    files: [
      {
        path: "registry/classic/blocks/form-dialog.tsx",
        type: "registry:component",
        target: "components/form-dialog.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/blocks/form-dialog.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["dialog", "form"],
    meta: undefined,
  },
  "form-sheet": {
    name: "form-sheet",
    description: "Common sheet of a form component",
    type: "registry:block",
    registryDependencies: [
      "https://ailabmn.gitlab.io/frontend/uilab/registry/r/confirmation.json",
    ],
    files: [
      {
        path: "registry/classic/blocks/form-sheet.tsx",
        type: "registry:component",
        target: "components/form-sheet.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/classic/blocks/form-sheet.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["sheet", "form"],
    meta: undefined,
  },
};
